title: "Lisa Lorraine Carson's Projects"
description: "...is a freelance podcaster. Her main podcast is called We Really Could and it's about ending billionaires."
url: "https://llcprojects.com"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Site settings
logo: "/assets/images/logo.png"

# Featured project - We Really Could
featured:
  title: "We Really Could"
  url: "https://wereallycould.com"
  blurb: "A weekly podcast about ending billionaires. Because $999,999,999 is enough to live like a king without actually being one."
  watch:
    - title: "Substack"
      url: "#"
    - title: "YouTube"
      url: "#"
  listen:
    - title: "Apple Podcasts"
      url: "#"
    - title: "Spotify Podcasts"
      url: "#"

# Other project links
projects:
  - title: "Silly little ding dongs"
    url: "#"
  - title: "The Light Is On"
    url: "https://thelightison.com"
  - title: "Do Something, Jackass"
    url: "https://dosomethingjackass.com"
  - title: "Colonial Bloomers"
    url: "https://colonialbloomers.com"

# Social links
socials:
  - title: "Instagram"
    url: "https://www.instagram.com/llcarson2/"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
